# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY . .

# Install project dependencies
RUN npm install

# Copy the rest of the application files to the container


# Expose the port that the app runs on (adjust if needed)
