name: My CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        run: |
          ssh ubuntu@44.205.23.93 "sudo -i && cd calcneat/calcneat-api/calcneatBe/ && git pull && npm install && pm2 restart index.js"
