# Step 1: Build the Angular application
FROM node:18.16.1 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build 

FROM nginx:alpine

COPY --from=build /app/dist/test-task/browser /usr/share/nginx/html

EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
